/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/22
 * 个人中心 ---- 挂账详情
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet,   
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
    ScrollView,
    ListView,
} from 'react-native';

// 引入购物车
import { ShoppingCart } from '../../../Components/index';

// 适配X
import { isIphoneX, ifIphoneX,clearNoNum,checkRate } from '../../../utils';


const Dimensions = require('Dimensions');
const {width,height} = Dimensions.get('window');

 //  账单
export class BillDetailVC extends Component{

    constructor(props) {
        super(props);
    
        this.state = {
           days: '7',
           money: '100',
           status: 1,  //  1 还清  0 待还
           brand: '马牌轮毂',
           data:  { number:'00000000',status:'已支付',url:'https://img-tmdetail.alicdn.com/bao/uploaded///img.alicdn.com/bao/uploaded/TB1M7oApTCWBKNjSZFtXXaC3FXa_!!0-item_pic.jpg_160x160q90.jpg',brand:'好好好品牌',price:'1000',spec:'80cm*80cm',mount:'2'},
           pay: {
               type: '货到付款',
               money: '999',
           },
           order: {
               waybill: '000000',  // 运单号
               ordernum: '000000', // 订单编号
               time: '2018/08/08', // 申请时间
               numbering: '00000', // 挂账编号
               payflow: '00000000', //支付流水
           },
           recordData: [
               ['6','2017/12/12','666','已还款'],
               ['6','2017/12/12','666','已还款'],
               ['6','2017/12/12','666','已还款'],
           ]
        }

    }

    // 返回
    back(option) {
        if(option == '返回') {
            this.props.navigation.goBack()
        }
    }

    // 头部
    renderHead() {
        return (
        <View style={[styles.head_box,this.state.status == 1? {}:{height:200}]}>
            <View style={[styles.head_inner,this.state.status == 1? {}:{height:"40%"}]}>
             {/* 期限 */}
               <View style={styles.date_limit}>
                    <Text style={styles.date_limit_txt1}>{this.state.days}天</Text>
                    <Text style={styles.date_limit_txt2}>总期限</Text>
               </View>

                <View style={styles.date_limit_line}></View>
             {/* 金额 */}
               <View style={styles.money_}>
                     <Text style={styles.date_limit_txt1}>{this.state.money}元</Text>
                     <Text style={styles.date_limit_txt2}>总金额</Text>
               </View>
            </View>

             {/* 还款状态 */}
             <View style={[styles.status_,this.state.status == 1?{} : {width:'100%',height:'60%',alignItems:'flex-start'}]}>
              {
                  this.state.status == 1 ? <Text style={styles.status_now}>当前状态：已全部还清</Text> :
              //  未还清
                  <View style={{width:'100%',height:'100%',justifyContent:'flex-start',}}>
                    <View style={{width:"100%",height:"40%",justifyContent:'center',alignItems:'flex-start',}}>
                       <Text style={[styles.status_now,{marginLeft:'4%'}]}>当前状态：等待还款</Text>
                        <View style={{width:120,height:'100%',position: 'absolute',right:'4%',justifyContent:'center',}}>
                            <TouchableHighlight onPress={() => {}} underlayColor="none" style={{width:'50%',height:'50%',backgroundColor: '#D23247',position:'absolute',right:0,borderRadius:3,}}>
                                <View style={{width:'100%',height:'100%',justifyContent:'center',alignItems:'center'}}>
                                    <Text style={{fontSize:12,color:"#ffffff",fontWeight:'600'}}>全部还清</Text>
                                </View>
                            </TouchableHighlight>
                        </View>
                   </View>

                   {/* 还款信息 */}
                   {this.renderFooter(['期限（天)','总金额（元)','未还金额（元)','还款日期'],this.state.recordData)}
                 </View>
              }
             </View>

        </View>
     )
    }

    //body部分
    renderBody() {
        return (
            <View style={[styles.body_box,]}>
               {/* 品牌 */}
                <View style={styles.body_brand}>
                    <Text style={styles.brand_txt}>{this.state.brand}</Text>
                </View>

                 {/* 购物车组件 */}
                <View style={{width:'100%',marginTop:'10%'}}>
                  <ShoppingCart data={this.state.data} />
                </View> 

                {/* 运费信息 */}
                <View style={styles.yun_info}>
                    <View style={styles.yun_inner}>
                        <Text style={[styles.yun_txt,{alignSelf:'flex-start'}]}>运费</Text>
                        <Text style={[styles.yun_txt,{alignSelf:'flex-end'}]}>{this.state.pay.type}</Text>
                    </View>

                    <View style={styles.yun_pay}>
                        <Text style={styles.yun_pay_txt1}>实付</Text>
                        <Text style={styles.yun_pay_txt2}>￥{this.state.pay.money}</Text>
                    </View>
                </View>

                 {/* 订单信息 */}
                 <View style={styles.orderBox}>
                    <View style={styles.order_inner}>
                        <Text style={[styles.order_inner_txt]}>运单编号：{this.state.order.waybill}</Text>
                        <Text style={[styles.order_inner_txt,{marginTop:5}]}>订单编号：{this.state.order.ordernum}</Text>
                        <Text style={[styles.order_inner_txt,{marginTop:5}]}>申请时间：{this.state.order.time}</Text>
                        <Text style={[styles.order_inner_txt,{marginTop:5}]}>挂账编号：{this.state.order.numbering}</Text>
                        <Text style={[styles.order_inner_txt,{marginTop:5}]}>支付流水：{this.state.order.payflow}</Text>                    
                    </View>
                </View>    
            </View>  
        )
    }

   // 底部渲染
    renderFooter(type,data) {
        return(
                <View style={[styles.footer_box,this.state.status == 1?{}:{marginTop:0}]}>
                 {this.state.status == 1 ?
                    <Text style={styles.record_txt}>还款记录</Text> : 
                    <View></View>
                    }
                      
                       <View style={styles.topl}>
                           {
                            type.map((val,key) => 
                               <View style={styles.foot_contain}>
                                  <Text style={styles.lanmu_}>{val}</Text>                    
                               </View>
                           )}
                       </View>
                    {/* 具体的记录 */}
                     {

                         data.map((val,key) => 
                           <View style={styles.value_box}>
                           {
                            val.map((val,key) => 
                               <View style={styles.val_inner_txt}>
                                   <Text style={styles.val_txt}>{val}</Text>                    
                               </View>
                           )}
                           </View>
                      )}     
                </View>
         )
    }

    //界面渲染
    renderPage() {
       return (
           <View style={{width:'100%',}}>
             {/* 渲染接口部分 */}
               {this.renderHead()}
               {this.renderBody()}
               {this.state.status == 1 ?  
               <View>
                 {this.renderFooter(['七天（天)','换款日期','换款金额 (元)','状态'],this.state.recordData)}
               </View> :
                <View></View>}
           </View>
       )
       
    }

    // 切换选项卡
    touch(key) {
     
    }


    componentDidMount() {
        // ....some api here 
     // 初始化数据  模拟请求过程
    //  clearTimeout(timer);
    //  const timer = setTimeout(() => {  
    //       this.fetchData('',this.datas); 
    //     },2000)
      if(this.state.status == 0) {
          this.setState({recordData:[['6','120000','120000','2018/04/04']]})
      }

    }

    render() {
        return (
            <View style={styles.container}>
             
             {/* 标题 */}
             <View style={styles.title}>

             <View style={{ width:"100%",height:ifIphoneX(90,75),alignItems: 'center',marginTop:10,justifyContent:'center',alignItems:'center'}}>
             
             <TouchableHighlight onPress={() => this.back('返回')} underlayColor="#ffffff" style={[styles.step_lefts,{width:30,marginLeft:20,zIndex:111}]}>
                <View style={[styles.step_lefts,{width:12,}]}>
                   <Image source={{uri:'icon_passback'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                </View>
              </TouchableHighlight>

              <Text style={{fontSize:16,fontWeight:"400",color:"#333333"}}>挂账详情</Text>
             
              </View>
    
             </View>


               {/* 订单列表 */}
              <View style={styles.shopList}>

                   <ScrollView 
                            ref={(r) => this.scrollview = r}
                            style={styles.list}  
                            // 水平滚动  
                            horizontal={false}  
                            // 是否显示水平滚动条  
                            showsHorizontalScrollIndicator={false}  
                            // 垂直滚动条
                            showsVerticalScrollIndicator = {false}
                            // 安页滚动  
                         //   pagingEnabled={true}  
  
                            //滚动动画结束时调用此函数  
                         //   onMomentumScrollEnd={(e)=>this.onAnimationEnd(e)}  
  
                            //开始拖拽  
                       //     onScrollBeginDrag={(e)=>this.setState({loaded:false,})}  
  
                            //停止拖拽  
                       //     onScrollEndDrag={(e)=> this.setState({loaded:true},() => { clearTimeout(tim);const tim = setTimeout(() => this.setState({timeout:false}),800)})}  
                          >  
                         {/* 列表数据渲染 */}
                       
                        {this.renderPage()}

                      </ScrollView>  

              </View>
            
      

            </View>
        );
    }
}




const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#f7f7f7',
    },
    title: { 
        width:"100%",
        height:75,
        marginTop: 0,
        alignItems: 'center',
        position:'absolute',
        zIndex:11,
        backgroundColor: "#ffffff",
        borderBottomWidth: 0.4,
        borderBottomColor: "#cccccc",
    },
    step: {
        width: '100%',
        height: '6%',
        marginTop:75,
        zIndex: 60,
        justifyContent: 'center',
        alignItems:'center',
        backgroundColor: '#ffffff',
        borderBottomWidth:.2,
        borderBottomColor:'#cccccc',
    },
    step_left: {
        width:"15%",
        height:30,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-start',
        position:'absolute',
    },
    step_lefts: {
        width:"15%",
        height:30,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-start',
        position:'absolute'
    },
    txt: {
        color:'#333333',
        fontSize:15,
    },
    list: {
        width: "100%",
        height:'100%',
   },
   shopList: {
        width: '100%',
        height:'100%',
   },
   head_box: {
       width:'100%',
       height:110,
       backgroundColor: '#ffffff',
       marginTop:75,
       justifyContent:'center',
       alignItems:'center'
    },
    head_inner: {
        width:'93%',
        height:'60%',
        alignItems:'center',
        justifyContent:'center',
        borderBottomWidth:1,
        borderBottomColor:'#f7f7f7'
    },
    date_limit: {
        width:'50%',
        height:'65%',
        position: 'absolute',
        alignSelf:'flex-start',
        justifyContent:'center',
        alignItems:'center',
    },
    date_limit_txt1:{
        fontSize:16,
        color:'#D23247',
        fontWeight:'500'
    },
    date_limit_txt2: {
        fontSize:17,
        color:'#666666',
        fontWeight:'400',
        marginTop:5,
    },
    date_limit_line:{
        width:.5,
        height:'50%',
        backgroundColor: '#cccccc',
    },
    money_:{
        width:'50%',
        height:'65%',
        position: 'absolute',
        alignSelf:'flex-end',
        justifyContent:'center',
        alignItems:'center'
    },
    status_:{
        width:'93%',
        height:'35%',
        alignItems:'flex-start',
        justifyContent:'center'
    },
    status_now: {
        fontSize:16,
        color:'#333333',
        fontWeight:'700'
    },
    body_box: {
        width:'100%',
        height:350,
        backgroundColor: '#f7f7f7',
        marginTop:75,
        justifyContent:'flex-start',
        alignItems:'flex-start',
        marginTop:10,
    },
    body_brand:{
        width:'100%',
        height:'10%',
        alignItems:'flex-start',
        justifyContent:'center',
        backgroundColor: '#FAFAFA',
    },
    brand_txt: {
        fontSize:17,
        color:'#333333',
        fontWeight:'400'
        ,marginLeft:'3%'
    },
    yun_info: {
        width:'100%',
        height:"25%",
        backgroundColor: '#ffffff',
        alignItems:'center',
        justifyContent:'center',marginTop:50,
    },
    yun_inner:{
        width:'93%',
        height:'50%',
        alignItems:'center',
        justifyContent:'center',
        borderBottomWidth:2,
        borderBottomColor:'#f7f7f7'
    },
    yun_txt: {
        fontSize:16,
        color:'#333333',
        fontWeight:'400',
        position:'absolute',
    },
    yun_pay:{
        width:'93%',
        height:'50%',
        alignItems:'center',
        justifyContent:'center',
    },
    yun_pay_txt1:{
        fontSize:16,
        color:'#333333',
        fontWeight:'400',
        position:'absolute',
        alignSelf:'flex-start'
    },
    yun_pay_txt2:{
        fontSize:16,
        color:'#F41E1E',
        fontWeight:'500',
        position:'absolute',
        alignSelf:'flex-end'
    },
    orderBox: {
        width:'100%',
        height:"40%",
        backgroundColor: '#ffffff',
        alignItems:'center',
        justifyContent:'center',
        marginTop:10,
    },
    order_inner:{
        width:'93%',
        height:'100%',
        alignItems:'flex-start',
        justifyContent:'center',
    },
    order_inner_txt:{
        fontSize:14,
        color:'#999999',
        fontWeight:'normal',
    },
    footer_box:{
        width:'100%',
        alignItems:'flex-start',
        justifyContent:'center',
        backgroundColor: '#ffffff',
        marginTop:20,
    },
    record_txt:{
        fontSize:15,
        color:'#333333',
        fontWeight:'600',
        marginLeft:'5%',
        marginBottom:'3%',
        marginTop:'3%',
    },
    topl:{
        width:'100%',
        height:30,
        backgroundColor: '#D23247',
        justifyContent:'center',
        flexDirection:'row'
    },
    foot_contain:{
        width:'25%',
        height:'100%',
        justifyContent:'center',
        alignItems:'center',
    },
    lanmu_:{
        fontSize:14,
        color:'#ffffff',
        fontWeight:'700',
    },
    value_box:{
        width:'100%',
        height:40,
        backgroundColor: '#ffffff',
        justifyContent:'center',
        flexDirection:'row'
    },
    val_inner_txt:{
        width:'25%',
        height:'100%',
        justifyContent:'center',
        alignItems:'center',
    },
    val_txt:{
        fontSize:14,
        color:'#333333',
        fontWeight:'normal',
    },
   
});
