/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/9.
 * 用户界面 ---- 个人中心 ----- 主界面
 */
import React, {Component} from 'react';
import {
     Platform,
     StyleSheet, 
     Text, 
     View, 
     Alert,
     Image,
     TouchableHighlight,
    } from 'react-native';

import { isIphoneX, ifIphoneX } from '../utils';


export class MineVC extends Component{

    constructor(props) {
        super(props);

        this.state = {
            username: '大神',
            userClassification : '普通用户',
            count: '666',
            imgUrl: 'icon_minhead',
            broadCast: '还款期限快到了，赶紧去还款吧！',
            money: '100.00',
        }
    }

    // 选项卡导航
    tabNav(key) {
        
        switch (key) {
            case 0 :
             this.props.navigation.navigate('BuyerMoneyVC')
              break;
            case  1:
              Alert.alert('我的挂账')
              break;
            case  2:
            this.props.navigation.navigate('BankCardVC')
              break;
            case  3:
              Alert.alert('邀请好友')
              break;
            case  4:
            this.props.navigation.navigate('AboutVC')
              break;
            case 'broadcast':
              Alert.alert('广播消息')
              break;
            case 'logout':
              Alert.alert('提示','是否要退出登录',[{
                  text:'确定',onPress: () => this.props.navigation.navigate('LoginVC')
                },{text:'取消',}])
              break;
            default:
              break;
        }
    }


    tabRender() {

        const itemArr = ['我的余额','我的挂账','我的银行卡','邀请好友','关于介绍'];
        const IconArr = ['icon_balance','icon_edit','icon_bank','icon_invite','icon_introduce']

        return itemArr.map((val,key) => {
            return (
             <TouchableHighlight onPress={() => this.tabNav(key)} underlayColor="#ffffff" style={styles.tabItem}>
                <View style={styles.tabItem}>
                  <View style={styles.tabItembox}>
                     <View style={styles.icon_left}>
                            <Image source={{ uri: IconArr[key] }} style={{ width:'100%',height:'100%',resizeMode:'contain'}}/>
                        </View>
                         <Text  style={styles.txt}>{val}</Text>
                         { val == '我的余额' ? <Text style={[styles.txt,{alignSelf:'flex-end',fontSize:13,color:'#F41E1E'}]}>{this.state.money}元</Text> : <Text style={styles.txt}></Text>
                        }
                      <View style={styles.icon_right}>
                         <Image source={{ uri: 'icon_arrow' }} style={{ width:'35%',height:'100%',resizeMode:'contain',alignSelf:'flex-end'}}/>
                      </View>
                      </View>
                </View>
            </TouchableHighlight>
            )
        })
       
    }

    componentDidMount() {
        //some  api ..
        // 获取个人中心的相关信息

    }



    render() {
        return (
            <View style={styles.container}>
            {/* 用户信息 */}
                <View style={styles.userInfo}>
                    <View style={styles.box}>
                     {/* 头像 */}
                        <View style={styles.user_head}>
                             <Image source={[{uri: 'mine_head'}]} style={[{width:90,height:90,resizeMode:'contain',position:'absolute',}]}/>
                             <Image source={[{uri: this.state.imgUrl}]} style={[{width:85,height:85,resizeMode:'cover',},this.state.imgUrl !== 'icon_head' ? {borderRadius:40,resizeMode:'cover'} : '']}/>
                        </View>
                    {/* 用户名 */}
                        <View style={styles.user_username}>
                            <Text style={{fontSize:20,color:'#FFFFFF',fontWeight:'600'}}>{this.state.username}</Text>
                            <Text style={{fontSize:16,color:'#FFFFFF',alignSelf:'flex-end',fontWeight:'400',marginTop:3,position:'absolute'}}>{this.state.userClassification}</Text>
                        </View>
                    {/* 账号 */}
                        <View style={styles.user_count}>
                            <Text style={{fontSize:15,color:'#FFFFFF',fontWeight:'600'}}>账号: {this.state.count}</Text>
                        </View>
                    </View>
                    
                </View>
          
              
                <View style={styles.tabs}>
                  <View style={{width:"100%",height:'100%',alignItems:'center',backgroundColor: '#f7f7f7',}}>
                 {/* 广播 */}
                    <View style={[styles.tabItem,{height:30,marginBottom:13}]}>
                     <TouchableHighlight onPress={() => this.tabNav('broadcast')} underlayColor="#ffffff" style={[styles.tabItem,{height:40}]}>
                      <View style={[styles.tabItembox,]}>
                        <View style={styles.icon_left}>
                            <Image source={{ uri: 'icon_attention2' }} style={{ width:'100%',height:'100%',resizeMode:'contain'}}/>
                        </View>
                        {/* 广播消息 */}
                         <Text style={[styles.txt,{fontSize:14}]}>{this.state.broadCast}</Text>
                      </View>
                     </TouchableHighlight>
                    </View>
             
                {/* 渲染选项卡 */}     
                   { this.tabRender() }

                 {/* 退出登录 */}
                 <TouchableHighlight onPress={() => this.tabNav('logout')} underlayColor="#ffffff" style={[{width:'100%',marginTop:10,height:45,justifyContent: 'center',}]}>
                    <View style={[{width:'100%',height:45,justifyContent: 'center',backgroundColor: '#ffffff',}]}>
                        <Text style={{color:'#C62F46',fontSize:17,fontWeight:'600',alignSelf:'center'}}>退出登录</Text>
                    </View>
                 </TouchableHighlight>
                </View>
               </View>

            </View>
        );
    }
}



const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f7f7f7',
    },
    userInfo: {
        width: "100%",
        height: "40%",
        backgroundColor:'#D23247',
        justifyContent: 'center',
        alignItems:'center',
    },
    box: {
        width:'50%',
        height:'50%',
        alignItems:'center',
        justifyContent:'center',
        marginTop: ifIphoneX("13%","5%"),
       
    },
    user_head: {
        width: 90,
        height: 90,
        marginTop: 30,
        borderRadius:45,
        alignItems:'center',
        justifyContent: 'center',
    },
    user_username: {
        width: '60%',
        height:'15%',
        marginTop:10, 
    },
    user_count: {
        width: '100%',
        height:'14%',
        alignItems:'center',
        justifyContent: 'center',
        marginTop:5,
    },
    tabs: {
        width:'100%',
        height: "70%",
        alignItems:'center',
        backgroundColor: '#f7f7f7',
    },
    tabItem: {
        width:'100%',
        height: ifIphoneX(60,50),
        alignItems:'center',
        justifyContent: 'center',
        backgroundColor:'#ffffff',
    },
    tabItembox: {
        width:'94%',
        height:'100%',
        justifyContent: 'center',
        alignItems:'center',
        borderBottomWidth: 1,
        borderBottomColor:'#f7f7f7',
    },
    icon_left: {
        width: 16,
        alignSelf: 'flex-start',
        justifyContent: 'center',
        alignItems:'center',
    },
    icon_right: {
        width: '6%',
        height:'100%',
        alignSelf: 'flex-end',
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 111,
        marginLeft:20,
    },
    txt: {
        position:'absolute',
        alignSelf:'flex-start',
        marginLeft:"7%",
        color:'#333333',
        fontSize: 16,
    }
 
});
