/**
 * generated by qiuchenglei on 2018/8/19
 * 购物车组件
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Image} from 'react-native';



export class ShoppingCart extends Component{

constructor(props) {
    super(props);
    this.state = {...this.props.data};
}

  render() {
    return (
        <View style={styles.container}>
            <View style={styles.box}>
               <View style={styles.in_}>
               {/* 购物车 物件图片 */}
                    <View style={styles.img}>
                      <Image source={{ uri:this.state.url}} style={{width:'100%',height:'100%',resizeMode:'cover'}} />
                    </View>
                 {/* 品牌 */}
                 <Text style={styles.brand}>{this.state.brand}</Text>  
                {/* 价格 */}
                     <Text style={styles.price}><Text style={{fontSize:12}}>￥</Text>{this.state.price}</Text>  

                {/* 规格 */}
                     <Text style={styles.spec}>{this.state.spec}</Text>  
                {/* 数量 */}
                     <Text style={styles.mount}>x{this.state.mount}</Text>    
               </View>
            </View>
        </View>
    )
  }
}



let styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'red',
    },
    box: {
        width:'100%',
        height:80,
        backgroundColor: '#ffffff',
        justifyContent: 'center',
        alignItems:'center'
    },
    in_: {
        width:'94%',
        height:'85%',
        justifyContent: 'center',
        alignItems:'center',
    },
    img: {
        width:'18%',
        height:'100%',
        alignSelf: 'flex-start',
    },
    brand:{
        fontSize:15,
        color:'#333333',
        position:'absolute',
        top:0,
        left:'24%'
    },
    price: {
        fontSize:15,
        color:'#F41E1E',
        position:'absolute',
        bottom:0,
        left:'24%'
    },
    spec: {
        fontSize:13,
        color:'#999999',
        position:'absolute',
        left:'24%'
    },
    mount: {
        fontSize:13,
        color:'#666666',
        position:'absolute',
        alignSelf:'flex-end'
    }


})

