/**
 * generated by qiuchenglei on 2018/8/15
 */

import React, {Component} from 'react';
import {createStackNavigator,createBottomTabNavigator,TabBarBottom} from 'react-navigation';

// 首页
import { Tab } from './ZBMain/MainVC';


//登录模块
import { 
    LoginVC,  // 密码登录
    MesLoginVC,   //  短信登录
    BackPasswordSetVC, //  密码找回 -- 设置新密码
    BackPasswordVC  // 密码找回
} from './ZBlogin';

//注册模块
import { 
   RegisterDealerVC,  // 注册商家选项
   RegisterIndexVC,   //  注册主界面
   RegisterLocationVC,  // 注册定位
   RegisterVC,    // 注册用户类型选项
   RegUserInfoVC  //  注册用户信息
} from './ZBregister';

//个人中心模块
import { 
   MineVC ,   // 主界面
   AboutVC,  //  关于质保
   BankCardAddVC, // 银行卡添加
   BankCardInfoVC, // 银行卡信息
   BankCardJiansheVC, // 建设银行服务协议
   BankCardKuaijieVC, // 快捷支付协议
   BankCardManagerVC, // 银行卡管理
   BankCardPhoneVC, //  银行卡手机验证
   BankCardSuccessVC, // 添加成功
   BankCardVC,   //   银行卡主界面
   BuyerMoneyVC,  //  买家余额界面
   CashVC,   //  提现界面
   DetailVC,   //  提现细节
   SuccessCashVC,  //  成功提现
} from './ZBMine';



export default class Router extends Component{
    render() {
        return (
           <Navigator />
        );
    }
}


const Navigator = createStackNavigator
({

    // 登录相关：
    LoginVC:{
      screen:LoginVC,        // 密码登录
     navigationOptions: {
            header: null 
        }
    },

    MesLoginVC:{
        screen:MesLoginVC,  // 短信登录
        navigationOptions: {
            header: null 
        }
    },

    // 密码找回
    BackPasswordVC:{
        screen:BackPasswordVC,  // 密码找回
        navigationOptions: {
            header: null 
        }
    },

    BackPasswordSetVC:{
        screen: BackPasswordSetVC, //  密码找回 -- 设置新密码
        navigationOptions: {
            header: null 
        }
    },



     // 注册相关：
    RegisterDealerVC:{
        screen: RegisterDealerVC,        //  注册商家选项
    //    navigationOptions: {
    //           header: null 
    //       }
      },

    RegisterIndexVC:{
        screen: RegisterIndexVC, //   注册主界面
        navigationOptions: {
            header: null 
        }
    },

    RegisterLocationVC:{
        screen: RegisterLocationVC, //   注册定位
        navigationOptions: {
            header: null 
        }
    },

    RegisterVC:{
        screen: RegisterVC, //   注册用户类型选项
        // navigationOptions: {
        //     header: null 
        // }
    },

    RegUserInfoVC :{
        screen: RegUserInfoVC,  //   注册用户信息
        navigationOptions: {
            header: null 
        }
    },




    //个人中心模块

    AboutVC :{
        screen: AboutVC,  //   关于质保
        navigationOptions: {
            header: null 
        }
    },

    
    BankCardAddVC:{
        screen:BankCardAddVC,  //   银行卡添加
        navigationOptions: {
            header: null 
        }
    },

    BankCardInfoVC:{
        screen:BankCardInfoVC,  //   银行卡信息
        navigationOptions: {
            header: null 
        }
    },

    BankCardJiansheVC:{
        screen:BankCardJiansheVC,  //   建设银行服务协议
        navigationOptions: {
            header: null 
        }
    },

    BankCardKuaijieVC:{
        screen:BankCardKuaijieVC, //   快捷支付协议
        navigationOptions: {
            header: null 
        }
    },

    BankCardManagerVC:{
        screen:BankCardManagerVC, //   银行卡管理
        navigationOptions: {
            header: null 
        }
    },

    BankCardPhoneVC:{
        screen:BankCardPhoneVC, //   银行卡手机验证
        navigationOptions: {
            header: null 
        }
    },

    BankCardSuccessVC:{
        screen:BankCardSuccessVC, //    添加成功
        navigationOptions: {
            header: null 
        }
    },

    BankCardVC:{
        screen:BankCardVC, //   银行卡主界面
        navigationOptions: {
            header: null 
        }
    },

    BuyerMoneyVC:{
        screen: BuyerMoneyVC, //   买家余额界面
        navigationOptions: {
            header: null 
        }
    },

    CashVC:{
        screen: CashVC, //   提现界面
        navigationOptions: {
            header: null 
        }
    },

    DetailVC:{
        screen: DetailVC, //   提现细节
        navigationOptions: {
            header: null 
        }
    },

    SuccessCashVC:{
        screen: SuccessCashVC, //    成功提现
        navigationOptions: {
            header: null 
        }
    },


    Home:{
        screen: Tab, //    首页
        navigationOptions: {
            header: null 
        }
    },


})