/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/13
 * 银行卡 ------ 主界面
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet,   
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
} from 'react-native';

// 适配X
import { isIphoneX, ifIphoneX,clearNoNum,checkRate } from '../../../utils';

const Dimensions = require('Dimensions');
const {width,height} = Dimensions.get('window');

 //  银行卡管理
export class BankCardVC extends Component{

    constructor(props) {
        super(props);

        this.state = {   
            bank: [
                {bank_name:'工商',bank_number:'0000',bank_logo:'icon_gongshang'},
                {bank_name:'建设',bank_number:'8909',bank_logo:'icon_jianshe'},
            ],
        }
    }

    // 返回
    back(option) {
        if(option == '返回') {
            this.props.navigation.goBack()
        }
    }

    //添加银行卡
    add() {
        this.props.navigation.navigate('BankCardAddVC')
    }

    // 银行卡管理
    manager(val) {
        this.props.navigation.navigate('BankCardManagerVC',{bank_number: val.bank_number})
    }


    componentDidMount() {
        // ....some api here 
    }

    render() {
        return (
            <View style={styles.container}>
             
             {/* 标题 */}
             <View style={styles.title}>

             <View style={{ width:"100%",height:ifIphoneX(90,75),alignItems: 'center',marginTop:10,justifyContent:'center',alignItems:'center'}}>
              <TouchableHighlight onPress={() => this.back('返回')} underlayColor="#ffffff" style={[styles.step_left,{width:30,marginLeft:20,zIndex:111}]}>
                <View style={[styles.step_left,{width:12,}]}>
                   <Image source={{uri:'icon_passback'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                </View>
              </TouchableHighlight>

                <Text style={{fontSize:17,fontWeight:"600",color:"#333333"}}>银行卡</Text>

                 {/* 添加按钮 */}
                 <TouchableHighlight onPress={() => this.add() } underlayColor="#ffffff" style={[styles.step_left,{width:30,marginRight:20,zIndex:111,alignSelf:'flex-end'}]}>
                    <View style={[styles.step_left,{width:20,}]}>
                      <Image source={{uri:'icon_add'}} style={{width:'100%',height:"100%",resizeMode:'contain',}}/>
                    </View>
                </TouchableHighlight>

              </View>
    
             </View>
            
        
          
            {/* 银行卡 */}
            
              <View style={styles.step}>
              {
              this.state.bank.map((val,key) =>
                 <View style={[styles.bankBox,key%2 !== 0 ? {backgroundColor: '#3C91DF',} : {backgroundColor:'#D23247'}]}>
                    {/* 银行类型 */}
                 <TouchableHighlight onPress={() => this.manager(val) } underlayColor={key%2 !== 0 ? {backgroundColor: '#3C91DF',} : {backgroundColor:'#D23247'}} style={{width:'100%',height:'100%',}}>
                     <View style={{width:'100%',height:'100%',}}>
                        <View style={{width:'12%',height:'50%',}}>
                          <Image source={{uri: val.bank_logo}} style={{width:'100%',height:"100%",resizeMode:'contain',}}/>
                        </View>
                      <View style={{width:'65%',height:'50%',position:'absolute',justifyContent:'center',alignItems:'center'}}>
                        <Text style={{fontSize:18,fontWeight:'700',color:'#FFFFFF'}}>中国{val.bank_name}银行</Text>
                      </View>
                   {/* 银行卡号 */}
                       <View style={{width:'100%',height:'50%',justifyContent:'center',alignItems:'center'}}>
                        <Text style={{fontSize:24,fontWeight:'500',color:'#FFFFFF',marginLeft:-75}}>**** &nbsp;**** &nbsp;****</Text>
                        <Text style={{fontSize:24,fontWeight:'500',color:'#FFFFFF',position:"absolute",alignSelf:'flex-end',right:40,top:5}}>{val.bank_number}</Text>
                      </View>

                     </View>
                  </TouchableHighlight>
                 </View>
                  )
                }
                
              </View>
            
            </View>
        );
    }
}



// const Tab=createBottomTabNavigator(
//     {


//     })



const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#f7f7f7',
    },
    title: { 
        width:"100%",
        height:75,
        marginTop: 0,
        alignItems: 'center',
        position:'absolute',
        zIndex:11,
        backgroundColor: "#ffffff",
        borderBottomWidth: 0.4,
        borderBottomColor: "#cccccc",
    },
    step: {
        width: '100%',
        height: '85%',
        marginTop:75,
        zIndex: 60,
        justifyContent: 'flex-start',
        alignItems:'center'
    },
    step_left: {
        width:"15%",
        height:30,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-start',
        position:'absolute'
    },
    bankBox: {
       width:'92%',
       height:"18%",
       marginTop:20,
       padding: 17,
       justifyContent: 'center',
       alignItems:'center',
       borderRadius: 5,
    }
   


    
});
