/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/13
 * 银行卡 ------ 银行卡管理
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet,   
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
} from 'react-native';

// 适配X
import { isIphoneX, ifIphoneX,clearNoNum,checkRate } from '../../../utils';

const Dimensions = require('Dimensions');
const {width,height} = Dimensions.get('window');

 //  银行卡管理
export class BankCardManagerVC extends Component{

    constructor(props) {
        super(props);

        this.state = {  
            isOpen: false, 
            bank_number: this.props.navigation.state.params.bank_number,
            isAgree: false,
        }
    }

    // 返回
    back(option) {
        if(option == '返回') {
            this.props.navigation.goBack()
        }
    }

    //添加银行卡
    add() {
        Alert.alert('添加')
    }


    //移除卡
    remove() {
        this.setState({isOpen: true})
    }

    // 同意解除
    isAgree(mes) {
        if(mes == 'agree') {
        this.setState({isAgree:true,})
        // 输入密码后解绑  这里需要输入密码解绑  这里缺少界面

       }else {
           this.setState({isOpen:false})
       }
    }


    componentDidMount() {
        // ....some api here 
    }

    render() {
        return (
            <View style={styles.container}>
             
             {/* 标题 */}
             <View style={styles.title}>

             <View style={{ width:"100%",height:ifIphoneX(90,75),alignItems: 'center',marginTop:10,justifyContent:'center',alignItems:'center'}}>
              <TouchableHighlight onPress={() => this.back('返回')} underlayColor="#ffffff" style={[styles.step_left,{width:30,marginLeft:20,zIndex:111}]}>
                <View style={[styles.step_left,{width:12,}]}>
                   <Image source={{uri:'icon_passback'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                </View>
              </TouchableHighlight>

                <Text style={{fontSize:17,fontWeight:"600",color:"#333333"}}>银行卡</Text>

                 {/* 添加按钮 */}
                 <TouchableHighlight onPress={() => this.add() } underlayColor="#ffffff" style={[styles.step_left,{width:30,marginRight:20,zIndex:111,alignSelf:'flex-end'}]}>
                    <View style={[styles.step_left,{width:20,}]}>
                      <Image source={{uri:'icon_add'}} style={{width:'100%',height:"100%",resizeMode:'contain',}}/>
                    </View>
                </TouchableHighlight>

              </View>
    
             </View>

               
          {/* 模态背景 */}
          {this.state.isOpen? <View style={styles.modalView}></View> : null}
          
          {/* 模态框 按钮 */}
            {
                  this.state.isOpen ?
                         <View style={styles.menu}>
                             
                             <View style={styles.modalViewStyle}>  
                               <TouchableHighlight onPress={() => this.isAgree('no')} underlayColor="#ffffff" style={{width:'5%',height:15,alignSelf:'flex-end',}}>                    
                                  <View style={{width:'100%',height:"100%",alignSelf:'flex-end',justifyContent:'center',alignItems:'center',marginTop:10,marginRight:10}}>
                                     <Image source={{uri:'mon_cancel'}} style={{width:'100%',height:"100%",resizeMode:'contain',alignSelf:'center'}}/>
                                  </View>
                                </TouchableHighlight>
                                <Text style={{fontSize:18,color:'#333333',fontWeight:'600',}}>提示</Text>
                             <View style={{width:'100%',height:'50%',borderBottomWidth:1,borderBottomColor:'#f4f4f4',justifyContent:'center',alignItems:"center"}}>
                                <Text style={{fontSize:14,color:'#333333',fontWeight:'normal',}}>解除后，银行服务将不可用</Text>
                             </View>

                              <TouchableHighlight onPress={() => this.isAgree('agree')} underlayColor="#ffffff" style={{width:'100%',height:"25%",justifyContent: 'center',alignItems: 'center',}}>
                                 <Text style={{fontSize:15,fontWeight: '400',color:'#D23247'}}>同意并解除绑定</Text>
                             </TouchableHighlight>

                             </View>
                         </View> 
                         :
                         <View></View>
 
               }
            
        
          
            {/* 银行卡 */}
            
              <View style={styles.step}>
                <View style={styles.remove}>
                    <View style={{width:"100%",height:'100%',justifyContent:'center',alignItems:'center'}}>
                        <Text style={{fontSize:16,color:"#333333",alignSelf:'flex-start'}}>储蓄卡（尾号{this.state.bank_number}）</Text>
                         <TouchableHighlight onPress={() => this.remove()} style={{alignSelf:'flex-end',position:'absolute',justifyContent:'center'}} underlayColor="#ffffff">
                            <Text style={{color:'#D23247',fontSize:16,alignSelf:'flex-end',position:'absolute'}}>解除绑定</Text>
                         </TouchableHighlight>
                    </View>
                </View>
                
              </View>
            
            </View>
        );
    }
}



// const Tab=createBottomTabNavigator(
//     {


//     })



const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#f7f7f7',
    },
    title: { 
        width:"100%",
        height:75,
        marginTop: 0,
        alignItems: 'center',
        position:'absolute',
        zIndex:11,
        backgroundColor: "#ffffff",
        borderBottomWidth: 0.4,
        borderBottomColor: "#cccccc",
    },
    step: {
        width: '100%',
        height: '85%',
        marginTop:75,
        zIndex: 60,
        justifyContent: 'flex-start',
        alignItems:'center'
    },
    step_left: {
        width:"15%",
        height:30,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-start',
        position:'absolute'
    },
    bankBox: {
       width:'92%',
       height:"18%",
       marginTop:20,
       padding: 17,
       justifyContent: 'center',
       alignItems:'center',
       borderRadius: 5,
    },
    modalView: {
        width:width,
        height:height,
        zIndex: 60,
        position:'absolute',
        backgroundColor: '#000000',
        opacity:.4,
        zIndex:333,
    },
    menu: {
        width: width,
        height:height,
        marginTop:-60,
        zIndex:7777,
        position:'absolute',
        alignItems:'center',
        justifyContent: 'center',
    },
    modalViewStyle: {
        width:'75%',
        height:"19%",
        position:'absolute',
        backgroundColor: '#ffffff',
        zIndex:444,
        marginTop:12,
        alignItems:'center',
        borderRadius: 10,
    },
    remove: {
        width:'100%',
        height:60,
        justifyContent: 'center',
        alignItems:'center',
        backgroundColor:'#ffffff',
        padding:12,
    }
   


    
});
