/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/14
 * 关于质保
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet,   
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
} from 'react-native';

// 适配X
import { isIphoneX, ifIphoneX,clearNoNum,checkRate } from '../../utils';

const Dimensions = require('Dimensions');
const {width,height} = Dimensions.get('window');

 //  关于质保
export class AboutVC extends Component{

    constructor(props) {
        super(props);

        this.state = {   
         
        }
    }

    // 返回
    back(option) {
        if(option == '返回') {
            this.props.navigation.goBack()
        }
    }


    componentDidMount() {
        // ....some api here 
    }

    render() {
        const infoArr = [
            {type:'质保',des:'质保APP'},
            {type:'功能',des:'质保APP是一款专门为老用户打造的一款全新智能APP方便用户操作，在此同时又可以获得保障'},
            {type:'企业',des:'质保APP'},
            {type:'客服',des:'质保APP'},
        ];
        return (
            <View style={styles.container}>
             
             {/* 标题 */}
             <View style={styles.title}>

             <View style={{ width:"100%",height:ifIphoneX(90,75),alignItems: 'center',marginTop:10,justifyContent:'center',alignItems:'center'}}>
             
             <TouchableHighlight onPress={() => this.back('返回')} underlayColor="#ffffff" style={[styles.step_lefts,{width:30,marginLeft:20,zIndex:111}]}>
                <View style={[styles.step_lefts,{width:12,}]}>
                   <Image source={{uri:'icon_passback'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                </View>
              </TouchableHighlight>

              <Text style={{fontSize:17,fontWeight:"600",color:"#333333"}}>关于介绍</Text>


            
    
              </View>
    
                 

             </View>
            
        
          
            {/* 质保LOGO */}
              <View style={styles.step}>
                 <View style={styles.successIcon}>
                   <Image source={{uri:'logo'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/> 
                 </View>
               
              </View>
            
            {/* 相关信息 */}
                <View style={styles.info}>
              {infoArr.map((val,key) =>
                 <View style={[styles.txt,key == '1' ? {height:70}:{}]}>
                     <View style={styles.txtInfo}>
                      <Text style={{fontSize:15,color:'#999999',fontWeight:'500'}}>{val.type}</Text>
                      <Text style={[{fontSize:15,color:'#333333',fontWeight:'normal',position:'absolute',width:'86%',left:'15%'},key == '1' ? {fontSize:15,lineHeight:20}:{}]}>{val.des}</Text>
                     </View>
                 </View>
              )}
               
              </View>

            </View>
        );
    }
}



// const Tab=createBottomTabNavigator(
//     {


//     })



const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#f7f7f7',
    },
    title: { 
        width:"100%",
        height:75,
        marginTop: 0,
        alignItems: 'center',
        position:'absolute',
        zIndex:11,
        backgroundColor: "#ffffff",
        borderBottomWidth: 0.4,
        borderBottomColor: "#cccccc",
    },
    step: {
        width: '100%',
        height: '30%',
        marginTop:75,
        zIndex: 60,
        justifyContent: 'center',
        alignItems:'center',
        backgroundColor: '#ffffff',
    },
    successIcon: {
       width:"40%",
       height:"100%",
       marginTop:0,
    },
    step_lefts: {
        width:"15%",
        height:30,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-start',
        position:'absolute'
    },
    info: {
        width:'100%',
        height:235,
        backgroundColor: '#ffffff',
        marginTop:10,
        justifyContent: 'flex-start',
        alignItems:'center',
    },
    txt: {
        width:'100%',
        height:55,
        justifyContent: 'center',
        alignItems:'center',
        borderBottomWidth:1,
        borderBottomColor:'#f7f7f7',
    },
    txtInfo: {
        width:'90%',
        height:'100%',
        justifyContent: 'center',
    }

   


    
});
