/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/8
 * 密码找回------ 普通用户 ------ 流程一 ---- 验证身份
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet, 
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
    Button,
    KeyboardAvoidingView,
    TextInput,
} from 'react-native';

// 隐藏软键盘
const dismissKeyboard = require('dismissKeyboard');

import { phoneReg } from '../utils';


export class BackPasswordVC extends Component{

    constructor(props) {
        super(props);
        this.state = {    
            phoneNumber:'',
            isGet: false, // 用户验证码获取状态
            code: '获取验证码',
            num: null,
            identifyingCode: '', // 验证码
        }
    }


    //触发焦点
    regOption(option) {
        switch(option) {
            case 'phone' :
               this.refs.phone.focus();
                break;
            case 'code' :
                this.refs.code.focus();
                break;
            default:
                break;
        }
        
    }

    back(option) {
        Alert.alert(option);
    }



      // 密码管理 验证码
      passWordManager(option) {
        switch(option) {
            case 'identifyingCode':   // 验证码
            if(this.state.phoneNumber) {
              if(phoneReg(this.state.phoneNumber)) {
            let num = 61;
        // 验证码倒计时 60s后重新获取
            clearInterval(timer);
            const timer = setInterval(() => {
              if(num<1) {
                  clearInterval(timer);
                  this.setState({isGet:false,code:'获取验证码'})
              } else {
                num--;
                this.setState({isGet:true,code: `${num}s后重发`,num})}
              }
            ,1000)
             }else {
                Alert.alert('错误','手机格式不正确',
                [{text:"我知道了", onPress: this.refs.phone.focus()}]
              );
             }

            } else {
                Alert.alert('错误','请输入手机号码',
                [{text:"我知道了", onPress: this.refs.phone.focus()}]
              );
            }
              break;
            default:
              break;
        }
    }

    // 下一步
    next(phoneNumber,identifyingCode) {

        if(phoneNumber && identifyingCode ) {
            // 手机号码
            if(phoneReg(phoneNumber)) {
                // 验证码验证
                // ....
                if(identifyingCode == 222) {
                    Alert.alert('进入下一步流程')
                    //  当验证无误时 跳转导航并传递参数   昵称要做字符处理
                    // ......

                    this.props.navigation.navigate('BackPasswordSetVC');

                   
                     
                    return true;
                }else {
                    Alert.alert('验证码错误','请输入验证码',[{text:'我知道了',onPress:
                     this.setState({identifyingCode:''})
                }])                 
                }
  
            }else {
                Alert.alert('号码错误','请输入您的手机号码',[{text:'我知道了',onPress:
                     this.setState({phoneNumber:''})
            }])   
            }

        }else {
            Alert.alert('空白','请输入信息',[{text:'我知道了',
           }])
        }
    }

    componentDidMount() {
        // ....some api here 
    }

    render() {
        return (
            <View style={styles.container}>
             
             {/* 标题 */}
             <View style={{ width:"100%",height:75,marginTop: 0,alignItems: 'center',borderBottomWidth:1,borderBottomColor:"#E6E6E6",position:'absolute',zIndex:11,backgroundColor: "#ffffff",}}>

             <View style={{ width:"100%",height:75,alignItems: 'center',marginTop:10,justifyContent:'center',alignItems:'center'}}>
              <TouchableHighlight onPress={() => this.props.navigation.goBack()} underlayColor="#ffffff" style={[styles.step_left,{width:30,marginLeft:20,zIndex:111}]}>
                <View style={[styles.step_left,{width:14,}]}>
                   <Image source={{uri:'icon_passback'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                </View>
              </TouchableHighlight>

                <Text style={{fontSize:18,fontWeight:"400",color:"#333333"}}>找回密码</Text>
              </View>

             </View>

                   {/* 步骤条 */}
                   <View style={styles.step}>
                        <View style={styles.stapbox}>

                             <View style={styles.inner}>
                                <View style={styles.steptop}>
                                 {/* 左 */}
                                    <View style={styles.step_left}>
                                         <Image source={{uri:'icon_step1'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                                    </View>

                                    <View style={styles.step_mid}></View>
                                {/* 右边 */}
                                     <View style={styles.step_right}>
                                         <Image source={{uri:'icon_step2'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                                    </View>
                                
                                </View>

                                {/* 底部 */}
                                 <View style={styles.bot}>
                                    <Text style={styles.step_text}>验证手机</Text>
                                    <Text style={[styles.step_text,{alignSelf:'flex-end',position:'absolute'}]}>设置密码</Text>
                                 </View>
                        
                            </View>
                    
                        </View>
                    </View>



                {/* 表单 */}
                <View style={styles.form}>

                     {/* 手机号 */}
                    <View style={[styles.info,styles.borders]}>

                      {/* 是否用户自己选择 */}
                        <TouchableHighlight onPress={() => this.regOption('phone')} underlayColor="#ffffff" style={styles.icon_location}>
                        
                        <View style={{width:"100%",height:"100%"}}>
                           <View style={styles.icon_locations}>
                                <Image source={{uri:'icon_phone'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                           </View>

            
                        {/* 请输入昵称 */}
                         <View style={styles.containers}>
                            <KeyboardAvoidingView behavior="padding" style={styles.containers}>
                                <TextInput
                                    underlineColorAndroid={'#ffffff'}
                                    placeholder="请输入手机号"
                                    style={{alignSelf:'flex-start',fontSize:17,marginLeft:-30}} 
                                    ref="phone"
                                    value={this.state.phoneNumber}
                                //获取焦点
                                //    onFocus={() => this.setState({isFocus:true})}
                                // 失去焦点
                                //    onBlur={() =>Reg()}
                                    onChangeText={(phoneNumber) => { this.setState({phoneNumber,});phoneNumber ? '' : dismissKeyboard()}}
                                // 限制只能输入数字
                                    keyboardType='numeric'
                                />
                             </KeyboardAvoidingView>
                            </View>
                          </View>
                        </TouchableHighlight>
                    </View>

                 {/* 验证码 */}
                    <View style={[styles.info,styles.borders]}>

                        <TouchableHighlight onPress={() => this.regOption('code')} underlayColor="#ffffff" style={styles.icon_location}>
                        
                        <View style={{width:"100%",height:"100%"}}>
                           <View style={styles.icon_locations}>
                                <Image source={{uri:'icon_safe'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                           </View>

            
                        {/* 验证码 */}
                         <View style={styles.containers}>
                            <KeyboardAvoidingView behavior="padding" style={styles.containers}>
                                <TextInput
                                    underlineColorAndroid={'#ffffff'}
                                    placeholder="请输入验证码"
                                    style={{alignSelf:'flex-start',fontSize:17,marginLeft:-30}} 
                                    ref="code"
                                    maxLength={4}
                                    value={this.state.identifyingCode}
                                //获取焦点
                                //    onFocus={() => this.setState({isFocus:true})}
                                // 失去焦点
                                //    onBlur={() =>Reg()}
                                onChangeText={(identifyingCode) => { this.setState({identifyingCode,});identifyingCode ? '' : dismissKeyboard() }}
                                // 限制只能输入数字
                                  //  keyboardType='numeric'
                                />
                             </KeyboardAvoidingView>
                        </View>


                           {/* 获取验证码 */}
                        <View style={[styles.icon_right,this.state.isGet ? {width:'35%'} :{width:'30%'},]}>
                             <TouchableHighlight onPress={() => this.state.isGet ? Alert.alert(`${this.state.num}秒后重试`) : this.passWordManager('identifyingCode')} underlayColor="#ffffff">
                                 <Text style={[{color:'#1e9acb2',fontSize:17,position:'absolute',alignSelf:'flex-end'},this.state.isGet ? {color:'#999999',}:{color:'#d23247'}]}>{this.state.code}</Text>
                            </TouchableHighlight>
                        </View>


                          </View>
                        </TouchableHighlight>
                    </View>


                 </View>


             {/* next */}
                <View style={styles.btn}>
    
                    <View style={styles.nextBtn}>
                        <TouchableHighlight onPress={() => this.next(this.state.phoneNumber,this.state.identifyingCode,)} underlayColor="##d23247" style={{width:'100%',height:'100%',justifyContent: 'center',alignItems: 'center',}}>
                            <Text style={{fontSize:18,fontWeight: '800',color:'#ffffff'}}>下一步</Text>
                        </TouchableHighlight>
                    </View>

                
                </View>
            
        
            </View>
        );
    }
}



// const Tab=createBottomTabNavigator(
//     {


//     })



const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#ffffff',
    },
    containers: {
        width: '80%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        marginLeft:'10%',
        alignSelf:"flex-start",
    },
    form: {
        width:"100%",
        height:100,
        backgroundColor:"#ffffff",
        justifyContent:"center",
        alignItems:"center",
        position:'absolute',
        zIndex:111,
        marginTop:240,
    },
    head: {
        width: '15%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'absolute',
        marginLeft:'10%',
        alignSelf: 'flex-end',
    },
    nav: {    
        width:'100%',
        height:25,
        marginTop: 30,
        position: 'absolute',
        zIndex: 11,
    },
    nav_icon: {
        width: '15%',
        height:'100%',
        alignSelf: 'flex-start',
    },
    btn: {
        width: '100%',
        height: '100%',
        backgroundColor: '#f7f7f7',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    borders: {
        borderBottomWidth: 0.7,
        borderBottomColor: "#E6E6E6",
    },
    icon_location: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems:'center',
    },
    icon_locations: {
        width: "4%",
        height: '100%',
        alignSelf: 'flex-start',
        marginLeft: 10,
        justifyContent: 'center',
        alignItems:'center',
    },
    info: {
        width: "95%",
        height: 50,
        backgroundColor: '#ffffff',
    },
    nextBtn: {
        width: '100%',
        height: 50,
        backgroundColor: '#d23247',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 11,
    },
    icon_right: {
        width: '5%',
        height: '65%',
        alignSelf: 'flex-end',
        position: 'absolute',
        justifyContent: 'center',
        alignItems:'flex-end'
    },
    step: {
        width:"100%",
        height:170,
        marginTop: 75,
        alignItems: 'center',
        position:'absolute',
        zIndex:11,
        backgroundColor: "#ffffff",
    },
    stapbox: {
        width:"40%",
        height:"100%",
        justifyContent:'center',
        alignItems:'center',
        marginTop: 25,
    },
    inner: {
        width:"100%",
        height:"50%",
        alignSelf:'center',
        marginBottom:40
    },
    steptop: {
        width: "80%",
        height: "50%",
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'center'
    },
    step_left: {
        width:"15%",
        height:"70%",
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-start',
        position:'absolute'
    },
    step_mid: {
        width:"50%",
        height:0.7,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'center',
        borderBottomWidth:0.7,
        borderBottomColor:'#CCCCCC'
    },
    step_right: {
        width:"15%",
        height:"70%",
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-end',
        position:'absolute'
    },
    bot: {
        width: "100%",
        height: "50%",
        marginTop:5,
    },
    step_text: {
        fontSize:14,
        fontWeight: 'normal',
        color:'#333333'
    }
});
