/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/7
 * 注册组件 ----  注册接口
 */
import React, {Component} from 'react';
import {
    Platform, 
    StyleSheet, 
    Text, 
    View, 
    Image,
    KeyboardAvoidingView,
    TextInput,
    Alert,
    TouchableHighlight,
    Button,
    AsyncStorage,
} from 'react-native';

// 引入工具函数
import { phoneReg,ifIphoneX } from '../utils';

// 隐藏软键盘
const dismissKeyboard = require('dismissKeyboard');


const PassRem = AsyncStorage.getItem('isRemberPassWord');
// console.log(PassRem._55);

export class RegisterIndexVC extends Component{

    static state = {
        behavior: 'padding',
      };
    

    constructor(props){
        super(props);
        this.state = {
            isText: false, // 用户输入状态
            isSelect: PassRem._55, //密码状态
            username: '',
            isFocus: false,
            password: '',
            isPassword: true,
            isGet: false, // 用户验证码获取状态
            code: '获取验证码',
            num: null,
            identifyingCode: '', // 验证码
        }
    }

    // 图标切换
    toggleIcon(cls) {
        // 点击取消按钮时 收起软键盘并清除表单
        switch(cls) {
            case 'cancel':
                dismissKeyboard();
                this.setState({
                    isText: true,
                    username: false,
                });
              break;
            case 'isPassword':
                this.setState({
                    isPassword: !this.state.isPassword,
                });
                break;
               
            default:
              break;
               
        }

        
    }

    // 密码管理 验证码
    passWordManager(option) {
        switch(option) {
            case 'identifyingCode':   // 验证码
            if(this.state.username) {
              if(phoneReg(this.state.username)) {
            let num = 61;
        // 验证码倒计时 60s后重新获取
            clearInterval(timer);
            const timer = setInterval(() => {
              if(num<1) {
                  clearInterval(timer);
                  this.setState({isGet:false,code:'获取验证码'})
              } else {
                num--;
                this.setState({isGet:true,code: `${num}s后重发`,num})}
              }
            ,1000)
             }else {
                Alert.alert('错误','手机格式不正确',
                [{text:"我知道了", onPress: this.refs.username.focus()}]
              );
             }

            } else {
                Alert.alert('错误','请输入手机号码',
                [{text:"我知道了", onPress: this.refs.username.focus()}]
              );
            }
              break;
            default:
              break;
        }
    }

    // 登录跳转
    register(username,password,identifyingCode) {
      dismissKeyboard(); 
      if(username && password && identifyingCode) {
        try {
                // 验证后台 验证手机格式
               // some api ...

                // 短信登录需要 验证用户是否是老用户还是新用户
        // 老用户 正常登录进入首页 保存用户登录信息
         if(phoneReg(username)) {
           if(username == '18706125795') {
             this.props.navigation.navigate('LoginVC')
              // 是否走登录流程
            }else {
                // 获取导航传递的数据
                const data = this.props.navigation.state.params.user_info
                console.log(data);

                this.props.navigation.navigate('Home');
                // 直接 跳转 注册流程
             }
            }else {
                Alert.alert('错误','手机格式不正确',
                [{text:"我知道了", onPress: this.refs.username.focus()}]);
           }
              
         } catch(err) {
                console.log(err);
          }
           // Alert.alert(username,password)
        }else {
            Alert.alert('请输入手机号码和密码')
       }
       
    }
   
    componentDidMount() {
       // some api ....
    }

    render() {
       
        return (
            <View style={[styles.container,this.state.isFocus ? {marginTop: -100} : '']}>

             {/* 标题 */}
             <View style={{ width:"100%",height:30,marginTop: ifIphoneX(50,30),alignItems: 'center',borderBottomWidth:1,borderBottomColor:"#E6E6E6"}}>
                <Text style={{fontSize:18,fontWeight:"600",color:"#5C5C5C"}}>注册</Text>
              </View>

             {/* 头像 */}
              <View style={styles.logo}>
                <Image source={{uri:'logo'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
              </View>

             {/* 表单 */}
              <View style={styles.from}>
                 <View style={styles.main}>

                  {/* 用户名 */}
                    <View style={[styles.li,{}]}>
                       {/* 图标 */}
                        <View style={styles.icon_left}>
                             <Image source={{uri:'icon_phone'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                        </View>
                     {/* 键盘输入 随视图变化*/}
                       <View style={styles.containers}>
                         <KeyboardAvoidingView behavior="padding" style={styles.containers}>
                            <TextInput
                                underlineColorAndroid={'#ffffff'}
                                placeholder="请输入手机号码"
                                style={styles.textInput} 
                                ref="username"
                            //获取焦点
                                onFocus={() => this.setState({isFocus:true})}
                            // 失去焦点
                                onBlur={() => this.state.username || this.state.identifyingCode ? this.setState({isFocus:true}) : this.setState({isFocus:false})}
                                value={ this.state.isText ? '' : this.state.username }
                                onChangeText={(username) => { this.setState({username,isText: false});username ? '' : dismissKeyboard()}}
                            // 限制只能输入数字
                                keyboardType='numeric'
                            />
                        </KeyboardAvoidingView>
                       </View>
                     {/* 图标切换 */}
                     <View style={styles.icon_right}>
                             <TouchableHighlight onPress={() => this.toggleIcon('cancel')} underlayColor="#ffffff">
                                <Image source={{uri:'icon_cancel'}} style={{width:'100%',height:"100%",resizeMode:'contain'}} />
                             </TouchableHighlight>
                        </View>
                    </View>

                    {/* 验证码 */}
                    <View style={[styles.li,{marginTop:15}]}>
                        {/* 图标 */}
                        <View style={styles.icon_left}>
                             <Image source={{uri:'icon_safe'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                        </View>
                     {/* 键盘输入 随视图变化*/}
                       <View style={styles.containers}>
                         <KeyboardAvoidingView behavior="padding" style={styles.containers}>
                            <TextInput
                                underlineColorAndroid={'#ffffff'}
                                placeholder="请输入验证码"
                                ref="identifyingCode"
                            // 获得焦点时 需要上移视图
                                onFocus={() => this.setState({isFocus:true})}
                            // 失去焦点
                                onBlur={() =>  this.state.username || this.state.identifyingCode ? this.setState({isFocus:true}) : this.setState({isFocus:false})}
                            // 最大长度4位
                                maxLength={4}  
                                style={styles.textInput} 
                                onChangeText={(identifyingCode) => { this.setState({identifyingCode,isText: false});identifyingCode ? '' : dismissKeyboard() }}
                          //  密文形式
                                secureTextEntry={false} 
                                keyboardType='numeric' 
                            />
                        </KeyboardAvoidingView>
                       </View>
                       {/* 获取验证码 */}
                       <View style={[styles.icon_right,this.state.isGet ? {width:'35%'} :{width:'30%'},]}>
                             <TouchableHighlight onPress={() => this.state.isGet ? Alert.alert(`${this.state.num}秒后重试`) : this.passWordManager('identifyingCode')} underlayColor="#ffffff">
                                 <Text style={[{color:'#1e9acb2',fontSize:14,marginTop:4,alignSelf:'flex-end'},this.state.isGet ? {color:'#999999',}:{color:'#d23247'}]}>{this.state.code}</Text>
                            </TouchableHighlight>
                        </View>
                    </View>

                  {/* 密码 */}
                     <View style={[styles.li,{marginTop:15}]}>
                        {/* 图标 */}
                        <View style={styles.icon_left}>
                             <Image source={{uri:'icon_lock'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                        </View>
                     {/* 键盘输入 随视图变化*/}
                       <View style={styles.containers}>
                         <KeyboardAvoidingView behavior="padding" style={styles.containers}>
                            <TextInput
                                underlineColorAndroid={'#ffffff'}
                                placeholder="请输入密码"
                                ref="password"
                                style={styles.textInput} 
                             // 获得焦点时 需要上移视图
                                onFocus={() => this.setState({isFocus:true})}
                             // 失去焦点
                                onBlur={() =>  this.state.username || this.state.identifyingCode ? this.setState({isFocus:true}) : this.setState({isFocus:false})}
                                onChangeText={(password) => {this.setState({password,isText: false});}}
                          //  密文形式
                                secureTextEntry={this.state.isPassword}  
                            />
                        </KeyboardAvoidingView>
                       </View>
                    {/* 图标切换 */}
                        <View style={styles.icon_right}>
                             <TouchableHighlight onPress={() => this.toggleIcon('isPassword')} underlayColor="#ffffff">
                                <Image source={{uri:'icon_1'}} style={{width:'100%',height:"100%",resizeMode:'contain'}} />
                             </TouchableHighlight>
                        </View>
                    </View>


                {/* 占位 */}
                    <View style={[styles.li,{height:"15%",borderBottomWidth: 0,}]}></View>

                {/* 登录按钮 */}
                    <View style={[styles.li,{borderRadius:25,marginTop:10,},this.state.username && this.state.password && this.state.identifyingCode ? {backgroundColor: '#d23247',} : {backgroundColor: '#e6e6e6',}]}>
                        <Button
                            onPress={ () => this.register(this.state.username,this.state.password,this.state.identifyingCode)}
                            title="注册"
                            color= {this.state.username && this.state.password && this.state.identifyingCode ? "#ffffff" : "#cfcfcf"}  
                            accessibilityLabel="Learn more about this purple button"
                        />
                    </View>

                    <View style={[styles.li,{alignItems:'center',height:"10%",borderBottomWidth: 0,marginTop:5,}]}>
                            <TouchableHighlight onPress={() => this.passWordManager('登录')} underlayColor="#ffffff">
                                 <Text style={{color:'#D23247',fontSize:13,fontWeight:'normal'}}>已有账号，去登陆</Text>
                            </TouchableHighlight>
                    </View>

                 </View>
              </View>
            </View>
        );
    }
}

// const Tab=createBottomTabNavigator(
//     {


//     })



const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#ffffff',
    },
    logo: {
        width:"100%",
        height:100,
        marginTop: 50,
        alignItems: 'center',
        color:'red',
    },
    from: {
        width: "100%",
        height: "30%",
        marginTop: 50,
        alignItems: 'center',
        justifyContent: 'center',
    },
    main: {
        width: "70%",
        height: "100%",
        alignItems: 'center',
    },
    li: {
        width: "100%",
        height: "20%",
        borderBottomWidth: 1,
        borderBottomColor: '#cccccc',
        justifyContent: 'center',
    },
    icon_left: {
        width: '10%',
        height: '60%',
    },
    icon_right: {
        width: '5%',
        height: '60%',
        alignSelf: 'flex-end',
        position: 'absolute'
    },
    containers: {
        width: '70%',
        height: '80%',
        justifyContent: 'center',
        position: 'absolute',
        marginLeft:'10%',
      },
    textInput: {
        height: '100%',
        fontSize: 14,
        marginLeft: 0,
        letterSpacing: 1,
      },
    text: {
        width:"23%",
        height:"80%",
        position:'absolute',
        marginLeft:'5%',
        justifyContent:'center',
        alignItems:'center',
        fontSize:10,
        fontWeight: 'normal',
    },
});
