/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/5
 * 注册流程------ 选择商户类别
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet, 
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
} from 'react-native';


export class RegisterDealerVC extends Component{

    constructor(props) {
        super(props);
    }

    regOption(option) {
        Alert.alert(option);
    }

    render() {
        return (
            <View style={styles.container}>
             {/* 导航器  待确认是否添加*/}
                {/* <View style={styles.nav}>
                    <View style={styles.nav_icon}>
                         <TouchableHighlight onPress={() => this.regOption('返回')} underlayColor="#ffffff">
                             <Text style={{fontSize:15,color:'#373535'}}>返回</Text>
                        </TouchableHighlight>
                    </View>
                </View> */}
            
            {/* 标题部分 */}
                <View style={styles.title}>
                    <Text style={{fontSize: 19,fontWeight: '500',color:'#333333'}}>您当前选择的是商家身份</Text>
                    <Text style={{fontSize: 15,color:'#666666',marginTop:10}}>进一步选择您的身份</Text>
                </View>

            {/* 用户注册类别 */}
                <View style={styles.option}>
                  {/* 买家 */}
                    <View style={styles.option_user}>
                         <TouchableHighlight onPress={() => this.regOption('经销商')} underlayColor="#ffffff">
                             <Image source={{uri:'pic_dealer'}} style={{width:'100%',height:"100%",resizeMode:'contain'}} />
                         </TouchableHighlight>
                         <Text style={{alignSelf:'center',marginTop:-30,color:'#393838',fontSize:15,}}>经销商身份</Text>
                    </View>

                 {/* 卖家 */}
                 <View style={[styles.option_user,{marginTop: 14,}]}>
                         <TouchableHighlight onPress={() => this.regOption('厂商')} underlayColor="#ffffff">
                             <Image source={{uri:'pic_vendor'}} style={{width:'100%',height:"100%",resizeMode:'contain'}} />
                         </TouchableHighlight>
                         <Text style={{alignSelf:'center',marginTop:-30,color:'#393838',fontSize:15}}>厂商身份</Text>
                    </View>

                </View>
            </View>
        );
    }
}



// const Tab=createBottomTabNavigator(
//     {


//     })



const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#ffffff',
    },
    // nav: {     待确认
    //     width:'100%',
    //     height:50,
    //     marginTop:-70,
    // },
    title: {
        width:'100%',
        height: 70,
        justifyContent:'center',
        alignItems: 'center',
        marginTop: 80,
    },
    option: {
        width: '100%',
        height: '50%',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 30,
    },
    nav_icon: {
        width: '20%',
        height:'100%',
        alignSelf: 'flex-start',
        marginLeft: 10,
    },
    option_user: {
        width: '40%',
        height: '50%',
        alignSelf: 'center',
    }
});
