/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/5
 * 注册流程------ 用户定位
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet, 
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
    Button,
} from 'react-native';


export class RegisterLocationVC extends Component{

    constructor(props) {
        super(props);
        this.state = {
            location: '我的位置',
        }
    }

    regOption(option) {
       switch(option) {
           case '返回':
            this.props.navigation.goBack();
            break;
           case '位置':
            break;
           case 'next':
            // 获取一些信息 并传递
            this.props.navigation.navigate('RegUserInfoVC',{location:'江苏'});
            break;
           default:
            break;
       }
    }

    render() {
        return (
            <View style={styles.container}>
             {/* 导航器  */}
                <View style={styles.nav}>
                    <View style={styles.nav_icon}>
                         <TouchableHighlight onPress={() => this.regOption('返回')} underlayColor="#ffffff">
                            <Image source={{uri:'icon_back'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                        </TouchableHighlight>
                    </View>
                </View>

             {/* 地图 */}
                <View style={styles.map}>
                
                </View>

             {/* 地理位置信息 */}
                <View style={styles.btn}>
                    <View style={styles.info}>
                      {/* 是否用户自己选择 */}
                        <TouchableHighlight onPress={() => this.regOption('位置')} underlayColor="#ffffff" style={styles.icon_location}>
                           <View style={styles.icon_location}>
                              <View style={styles.icon_locations}>
                                <Image source={{uri:'icon_location2'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                              </View>
                                <Text style={{fontSize: 15,position:'absolute',alignSelf:'flex-start',marginLeft:"8%",color:'#333333',fontWeight:'normal'}}>{this.state.location}</Text>
                           </View>
                        </TouchableHighlight>
                    </View>
                   
                    <View style={styles.nextBtn}>
                        <TouchableHighlight onPress={() => this.regOption('next')} underlayColor="##d23247" style={{width:'100%',height:'100%',justifyContent: 'center',alignItems: 'center',}}>
                            <Text style={{fontSize:18,fontWeight: '800',color:'#ffffff'}}>下一步</Text>
                        </TouchableHighlight>
                    </View>

                
                </View>
            
        
            </View>
        );
    }
}



// const Tab=createBottomTabNavigator(
//     {


//     })



const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#ffffff',
    },
    nav: {    
        width:'100%',
        height:25,
        marginTop: 30,
        position: 'absolute',
        zIndex: 11,
    },
    nav_icon: {
        width: '15%',
        height:'100%',
        alignSelf: 'flex-start',
    },
    map: {
        width: '100%',
        height: '80%',
    },
    btn: {
        width: '100%',
        height: '20%',
        backgroundColor: '#f7f7f7',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    icon_location: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems:'center',
    },
    icon_locations: {
        width: "4%",
        height: '50%',
        alignSelf: 'flex-start',
        marginLeft: 10,
    },
    info: {
        width: "100%",
        height: 50,
        marginBottom: 50,
        backgroundColor: '#ffffff',
    },
    nextBtn: {
        width: '100%',
        height: 50,
        backgroundColor: '#d23247',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 11,
    }
});
