/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/16
 * 请求封装
 */


/*
     *  get请求
     *  url:请求地址
     *  params:参数
     *  callback:回调函数
     * */

    function GET(url,params,callback){
        if (params) {
            let paramsArray = [];
            //拼接参数
            Object.keys(params).forEach(key => paramsArray.push(key + '=' + params[key]))
            if (url.search(/\?/) === -1) {
                url += '?' + paramsArray.join('&')
            } else {
                url += '&' + paramsArray.join('&')
            }
        }
        
        fetch(url,{
            method: 'GET',
        })
            .then((response) => {
                callback(response)
            })
            .catch((error) => {
                alert(error)
            });
    }


    /*
     *  post请求
     *  url:请求地址
     *  params:参数,
     *  callback:回调函数
     * */
    function PostJSON(url,params,callback){
        
        fetch(url,{
            method: 'POST',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
            },
            body:JSON.stringify(params)
        })
            .then((response) => response.json())
            .then((responseJSON) => {
                callback(responseJSON)
            })
            .catch((error) => {
                console.log("error = " + error)
            });
    }

    /*
     *  post请求
     *  url:请求地址
     *  params:参数
     *  callback:回调函数
     * */
    function PostForm(url,params,callback){
        
        fetch(url,{
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body: params
        })
            .then((response) => response.json())
            .then((responseJSON) => {
                callback(responseJSON)
            })
            .catch((error) => {
                console.log("error = " + error)
            });
    }

    export const Http = { GET, PostJSON, PostForm };

   // Http.GET('http://180.76.162.182:8090/api/v1/user/phone','',(data) => console.log(data))


   // Http.PostJSON('http://180.76.162.182:8090/api/v1/user',{username:'111',password:'111'},(data) => console.log(data))









