/**
 * generated by qiuchenglei on 2018/8/4
 * 工具函数封装
 */

import {
    Alert,
    Dimensions, 
    Platform, 
} from 'react-native';

// 手机号验证
export const phoneReg = (phoneNumber) => {
    const sMobile = phoneNumber;
    if(!(/^1[3|4|5|8][0-9]\d{4,8}$/.test(sMobile))) { 
        return false; 
    } 
    return true;
}

// 金额校验 @return  { 'number' } 返回值只能是：1.数字、小数点最多两位、001转为1
export function clearNoNum(val){
 
    if(val !=''&& val.substr(0,1) == '.'){
        val="";
    }
    val = val.replace(/^0*(0\.|[1-9])/, '$1');
    val = val.replace(/[^\d.]/g,"");  
    val = val.replace(/\.{2,}/g,".");   
    val = val.replace(".","$#$").replace(/\./g,"").replace("$#$",".");    
 //   val = val.replace(/^(\-)*(\d+)\.(\d\d).*$/,'$1$2.$3');    限制输入的小数位
    if(val.indexOf(".")< 0 && val !=""){
        if(val.substr(0,1) == '0' && val.length == 2){
            val = val.substr(1,val.length);	
        }
    } 
    return val;   
}  

// 数字校验
export function checkRate(value) {
      //　const reg = /^[0-9]+.?[0-9]*$/; //判断字符串是否为数字 
       
         const reg2 = /^\d+(\.\d{0,})?$/;  //判断正数 
    
    　　if (!reg2.test(value)) {
    　　　　return false;
    　　}
    return true;
}


// 身份证号验证
export const IDNUMBER = (ID) => {
    const regIdNo = /(^\d{15}$)|(^\d{18}$)|(^\d{17}(\d|X|x)$)/; 
    if(!regIdNo.test(ID)){ 
     return false; 
    }
    return true;
} 

//真实姓名验证
export const USERNAME = (NAME) => {
    const regName =/^[\u4e00-\u9fa5]{2,4}$/; 
    if(!regName.test(NAME)){ 
    return false; 
    }
    return true;
}

// 弹出框
export const Tips = (AlertObj) => {
    Alert.alert(AlertObj.title, AlertObj.msg, [{text: AlertObj.endMsg, onPress: AlertObj.callback}]);
}



// 判断是否为IphoneX设备
export function isIphoneX() {
    let dimen = Dimensions.get('window');
    return (
        Platform.OS === 'ios' &&
        !Platform.isPad &&
        !Platform.isTVOS &&
        (dimen.height === 812 || dimen.width === 812)
    );
}

// 针对苹果设备返回的样式
export function ifIphoneX(iphoneXStyle, regularStyle) {
    if (isIphoneX()) {
        return iphoneXStyle;
    } else {
        return regularStyle
    }
}

// 银行卡号校验
export function BankCardCheck(content) {  
    const regex = /^([1-9]{1})(\d{14}|\d{18})$/;
    if (regex.test(content)) {  
        return true;  
    }  
    return false;  
}  

