/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/10
 * 个人中心------ 我的余额 
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet, 
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
    Button,
} from 'react-native';

// 隐藏软键盘
const dismissKeyboard = require('dismissKeyboard');

// 适配X
import { isIphoneX, ifIphoneX } from '../../../utils';


 //  我的余额组件
export  class BuyerMoneyVC extends Component{

    constructor(props) {
        super(props);
        this.state = {    
           money:'100.00',  // 余额
        }
    }

    back(option) {
        if(option == '返回') {
            this.props.navigation.goBack()
        }else {
            this.props.navigation.navigate('DetailVC')
        }
    }



    // 下一步
    next() {
        this.props.navigation.navigate('CashVC',{money: this.state.money })
    }

    componentDidMount() {
        // ....some api here 
    }

    render() {
        return (
            <View style={styles.container}>
             
             {/* 标题 */}
             <View style={{ width:"100%",height:75,marginTop: 0,alignItems: 'center',position:'absolute',zIndex:11,backgroundColor: "#D23247",}}>

             <View style={{ width:"100%",height:ifIphoneX(90,75),alignItems: 'center',marginTop:10,justifyContent:'center',alignItems:'center'}}>
              <TouchableHighlight onPress={() => this.back('返回')} underlayColor="#D23247" style={[styles.step_left,{width:30,marginLeft:20,zIndex:111}]}>
                <View style={[styles.step_left,{width:12,}]}>
                   <Image source={{uri:'mine_back'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                </View>
              </TouchableHighlight>

                <Text style={{fontSize:17,fontWeight:"600",color:"#ffffff"}}>我的余额</Text>
                {/* 查看明细 */}
                 <TouchableHighlight onPress={() => this.back('查看明细')} underlayColor="#D23247" style={{position:'absolute',alignSelf:'flex-end',}}>
                    <View style={{width:'100%',height:'100%'}}>
                        <Text style={{fontSize:15,fontWeight:"600",color:"#ffffff",marginRight:20}}>查看明细</Text>
                    </View>
                </TouchableHighlight>

              </View>

             </View>

                   {/* 余额信息 */}
                   <View style={styles.step}>
                       <View style={styles.txt}>
                            <Text style={{color:'#ffffff',fontSize:14, marginLeft:20,marginTop:70,fontWeight:'600'}}>账户余额（元）</Text>
                       </View>

                        <View style={styles.txt}>
                            <Text style={{color:'#ffffff',fontSize:35,marginLeft:20,marginTop:60,fontWeight:'400'}}>{this.state.money}元</Text>
                        </View>
                    </View>



             {/* 提现 */}
                <View style={styles.btn}>
    
                    <View style={styles.nextBtn}>
                        <TouchableHighlight onPress={() => this.next()} underlayColor="##d23247" style={{width:'100%',height:'100%',justifyContent: 'center',alignItems: 'center',}}>
                            <Text style={{fontSize:17,fontWeight: '800',color:'#ffffff'}}>提现</Text>
                        </TouchableHighlight>
                    </View>

                
                </View>
            
        
            </View>
        );
    }
}




const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#f7f7f7',
    },
   step: {
       width: '100%',
       height: '30%',
       backgroundColor: '#D23247',
       justifyContent: 'center',
       alignItems: 'flex-start',
   },
    nav: {    
        width:'100%',
        height:25,
        marginTop: 30,
        position: 'absolute',
        zIndex: 11,
    },
    txt: {
        width:'100%',
    },
    nav_icon: {
        width: '15%',
        height:'100%',
        alignSelf: 'flex-start',
    },
    btn: {
        width: '100%',
        height: '70%',
        backgroundColor: '#f7f7f7',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    borders: {
        borderBottomWidth: 0.7,
        borderBottomColor: "#E6E6E6",
    },
    info: {
        width: "95%",
        height: 50,
        backgroundColor: '#ffffff',
    },
    nextBtn: {
        width: '100%',
        height: 50,
        backgroundColor: '#d23247',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 11,
    },
    icon_right: {
        width: '5%',
        height: '65%',
        alignSelf: 'flex-end',
        position: 'absolute',
        justifyContent: 'center',
        alignItems:'flex-end'
    },
    step_left: {
        width:"15%",
        height:"70%",
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-start',
        position:'absolute'
    },
});
