/**
 * Created by yangu on 2018/8/4.
 * generated by qiuchenglei on 2018/8/12
 * 个人中心------ 提现
 */
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet,   
    Text, 
    View, 
    Image,
    Alert,
    TouchableHighlight,
    Button,
    TextInput,
    KeyboardAvoidingView,
} from 'react-native';

// 适配X
import { isIphoneX, ifIphoneX,clearNoNum,checkRate } from '../../../utils';

const Dimensions = require('Dimensions');
const {width,height} = Dimensions.get('window');

 //  提现
export class CashVC extends Component{

    constructor(props) {
        super(props);

        this.state = {   
           isOpen: false,  // 模态框状态
           remainMoney: 89, // 获取余额
           bank: {
               who: '工商',    // 通过后台获取
               lastNumber: '8999',
           },
           money:  this.props.navigation.state.params.money,  // 初始化余额
        }
    }

    // 返回
    back(option) {
        if(option == '返回') {
            this.props.navigation.goBack()
        }
    }

    Menu(item) {
        this.setState({isOpen:false});
    }


      // 下一步
      next(option,val,bank) {
        switch(option) {
            //  提现流程
            case 'cash':
              if(bank) {
                  if(val) {
                  // 校验输入是金额数目
                  if(checkRate(val)) {
                    // 二次校验
                    let value = clearNoNum(val);
                    if(value > this.state.remainMoney) {
                        this.setState({isOpen: true})
                    }else {
                       // Alert.alert(value);  走后台提交
                       this.props.navigation.navigate('SuccessCashVC')
                    }
                   
                    // .... some api 
                        
                  }else {
                      Alert.alert('金额数目只能为数字')
                  }
                }else {
                    Alert.alert('请输入金额')
                }
                
              }else {
                  Alert.alert('请选择银行卡')
              }
              break;
            // 更换银行卡
            case 'changeCard':
              Alert.alert('银行卡')  
              break;
            default:
              break;

        }
  
    }




    componentDidMount() {
        // ....some api here 
    }

    render() {
        return (
            <View style={styles.container}>
             
             {/* 标题 */}
             <View style={styles.title}>

             <View style={{ width:"100%",height:ifIphoneX(90,75),alignItems: 'center',marginTop:10,justifyContent:'center',alignItems:'center'}}>
              <TouchableHighlight onPress={() => this.back('返回')} underlayColor="#ffffff" style={[styles.step_left,{width:30,marginLeft:20,zIndex:111}]}>
                <View style={[styles.step_left,{width:12,}]}>
                   <Image source={{uri:'icon_passback'}} style={{width:'100%',height:"100%",resizeMode:'contain'}}/>
                </View>
              </TouchableHighlight>

                <Text style={{fontSize:17,fontWeight:"600",color:"#333333"}}>提现</Text>
    
              </View>
    
                 

             </View>
            
          {/* 模态背景 */}
                {this.state.isOpen? <View style={styles.modalView}></View> : null}
          
             {/* 模态框 按钮 */}
               {
                     this.state.isOpen ?
                            <View style={styles.menu}>
                                
                                <View style={styles.modalViewStyle}>  
                                  <TouchableHighlight onPress={() => this.setState({isOpen:false})} underlayColor="#ffffff" style={{width:'5%',height:15,alignSelf:'flex-end',}}>                    
                                     <View style={{width:'100%',height:"100%",alignSelf:'flex-end',justifyContent:'center',alignItems:'center',marginTop:10,marginRight:10}}>
                                        <Image source={{uri:'mon_cancel'}} style={{width:'100%',height:"100%",resizeMode:'contain',alignSelf:'center'}}/>
                                     </View>
                                   </TouchableHighlight>
                                   <Text style={{fontSize:18,color:'#333333',fontWeight:'600',}}>提示</Text>
                                <View style={{width:'100%',height:'50%',borderBottomWidth:1,borderBottomColor:'#f4f4f4',justifyContent:'center',alignItems:"center"}}>
                                   <Text style={{fontSize:14,color:'#333333',fontWeight:'normal',}}>您输入的提款金额超过您账户的余额，</Text>
                                   <Text style={{fontSize:14,color:'#333333',fontWeight:'normal',marginTop:5,}}>请重新输入提款金额</Text>
                                </View>

                                 <TouchableHighlight onPress={() => this.setState({isOpen:false})} underlayColor="#ffffff" style={{width:'100%',height:"25%",justifyContent: 'center',alignItems: 'center',}}>
                                    <Text style={{fontSize:15,fontWeight: '400',color:'#D23247'}}>确定</Text>
                                </TouchableHighlight>

                                </View>
                            </View> 
                            :
                            <View></View>
    
                  }
                
              <View style={styles.step}>

                  {/* 银行卡 */}
                 <TouchableHighlight onPress={() => this.next('changeCard')} underlayColor="#ffffff" style={[styles.bankBox,]}>
                   <View style={[styles.bankBox,{marginTop:0},]}>
                       <View style={[{width:"105%",height:"90%",alignItems:'center',},]}>
                        {
            // 判断是否选择了银行卡
            this.state.bank.who ?
                  <View  style={{width:"100%",height:"90%",alignItems:'center',}}>
                           <View style={{width:'15%',height:'100%',alignSelf:'flex-start',position:'absolute',}}>
                              <Image source={{uri:'bg_bank'}} style={{width:'100%',height:"100%",resizeMode:'contain',zIndex:333,}} />
                            </View>
                        {/* 银行卡logo */}
                        <View style={{width:'15%',height:'100%',alignSelf:'flex-start',justifyContent:'center',alignItems:'center'}}>
                          <Image source={{uri:'logo_gongshang'}} style={{width:'70%',height:"70%",resizeMode:'contain',zIndex:333,}} />
                        </View>
                        {/* 银行卡信息 */}
                         <View style={{width:'50%',height:'100%',position:'absolute',alignSelf:'flex-start',justifyContent:'center',alignItems:'flex-start'}}>
                                <Text style={{fontSize:17,color:'#333333',marginLeft:"40%"}}>{this.state.bank.who}银行</Text>
                                <Text style={{fontSize:18,color:'#333333',marginLeft:"40%"}}>尾号{this.state.bank.lastNumber}</Text>
                         </View>
                 </View>
                         : 
                         <View style={{width:'100%',height:'100%',justifyContent:'center'}}>
                           <Text style={{fontSize:21,color:'#3333333',fontWeight:'300',marginLeft:5,}}>选择银行卡</Text>
                         </View>
                        }
                        {/* icon */}
                        <View style={{width: 10,height:'100%',alignSelf:'flex-end',position:'absolute'}}>
                         <Image source={{uri:'icon_rights'}} style={{width:'100%',height:"100%",resizeMode:'contain',zIndex:333,}} />
                        </View>
                         
                       </View>
                    
                   </View>
                  </TouchableHighlight>


              {/* 提现金额 */}
                 <TouchableHighlight underlayColor="#ffffff" style={[styles.bankBox,{marginTop:20}]}>
                   <View style={[styles.bankBox,{marginTop:0},]}>
                     
                       <View style={{width:"105%",height:"90%",alignItems:'center',}}>
                           <Text style={{fontSize:30,color:'#333333',fontWeight:'400',alignSelf:'flex-start',marginTop:21,}}>￥</Text>  
                        {/* 输入表单 */}
                         <View style={{width:'100%',height:'100%',position:'absolute',alignSelf:'flex-start',justifyContent:'center',alignItems:'flex-start'}}>
                            <KeyboardAvoidingView behavior="padding" style={[styles.moneyInpu,!this.state.money ? {height:"65%"} : {}]}>
                                <TextInput
                                    underlineColorAndroid={'#ffffff'}
                                    placeholder="请输入提现金额"
                                    ref="password"
                                    style={[styles.textInput,this.state.money ? {}:{fontSize:16,height:-20}]} 
                                    value={this.state.money.toString()}
                                    maxLength={12}
                                // 获得焦点时
                                //   onFocus={() => this.setState({isFocus:true})}
                                // 失去焦点
                                //  onBlur={() =>  this.state.username || this.state.identifyingCode ? this.setState({isFocus:true}) : this.setState({isFocus:false})}
                                    onChangeText={ (money) =>  this.setState({money,}) } 
                            //  密文形式
                                 //   secureTextEntry={this.state.isPassword}  
                                />
                            </KeyboardAvoidingView>
                         </View>
                        {/* icon */}
                        <View style={{width:"7%",height:'100%',alignSelf:'flex-end',position:'absolute',justifyContent:'center'}}>
                           <Text style={{fontSize:16,color:'#333333',alignSelf:'flex-end',marginTop:17}}>元</Text>
                        </View>
                         
                       </View>
                   </View>
                  </TouchableHighlight>

                  </View>  


                   {/* 提现 */}
                <View style={styles.btn}>
    
                    <View style={styles.nextBtn}>
                        <TouchableHighlight onPress={() => this.next('cash',this.state.money.toString(),this.state.bank.who)} underlayColor="#d23247" style={{width:'100%',height:'100%',justifyContent: 'center',alignItems: 'center',}}>
                            <Text style={{fontSize:17,fontWeight: '800',color:'#ffffff'}}>提现</Text>
                        </TouchableHighlight>
                    </View>

                
                </View>


            </View>
        );
    }
}




const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: '#f7f7f7',
    },
    title: { 
        width:"100%",
        height:75,
        marginTop: 0,
        alignItems: 'center',
        position:'absolute',
        zIndex:11,
        backgroundColor: "#ffffff",
        borderBottomWidth: 0.4,
        borderBottomColor: "#cccccc",
    },
    step: {
        width: '100%',
        height: '85%',
        marginTop:75,
        zIndex: 60,
    },
   list: {
        width: "100%",
   },
   moneyInpu: {
       width:'100%',
       height:'100%',
       marginLeft:'9%',
       position:'absolute',
       alignSelf:'flex-start',
       justifyContent:'flex-end',
       alignItems:'flex-start',
    },
    textInput: {
        fontSize:40,
        width:'100%',
        height:'90%',
    },
   bankBox: {
        width:'100%',
        height:90,
        marginTop:13,
        padding: 10,
        justifyContent: 'center',
        alignItems:'center',
        backgroundColor: '#ffffff',
        zIndex: 0,
 
    },
    nav: {    
        width:'100%',
        height:25,
        marginTop: 30,
        position: 'absolute',
        zIndex: 11,
    },
    txt: {
        width:'100%',
    },
    nav_icon: {
        width: '15%',
        height:'100%',
        alignSelf: 'flex-start',
    },
    info: {
        width: "95%",
        height: 50,
        backgroundColor: '#ffffff',
    },
    icon_right: {
        width: '5%',
        height: '65%',
        alignSelf: 'flex-end',
        position: 'absolute',
        justifyContent: 'center',
        alignItems:'flex-end'
    },
    step_left: {
        width:"15%",
        height:30,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'flex-start',
        position:'absolute'
    },
   
    modalView: {
        width:width,
        height:height,
        zIndex: 60,
        position:'absolute',
        backgroundColor: '#000000',
        opacity:.4,
        zIndex:333,
    },
    menu: {
        width: width,
        height:height,
        marginTop:-60,
        zIndex:7777,
        position:'absolute',
        alignItems:'center',
        justifyContent: 'center',
    },
    modalViewStyle: {
        width:'75%',
        height:"19%",
        position:'absolute',
        backgroundColor: '#ffffff',
        zIndex:444,
        marginTop:12,
        alignItems:'center',
        borderRadius: 10,
    },
    btn: {
        width: '100%',
        height: '100%',
        backgroundColor: '#f7f7f7',
        justifyContent: 'flex-end',
        alignItems: 'center',
        position: 'absolute',
    },
    nextBtn: {
        width: '100%',
        height: 50,
        backgroundColor: '#d23247',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 11,
    },
    
});
